In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/train.csv",
    parse_dates=["date"])

/var/folders/qd/66x74wkn0c7255_dtgx43p000000gn/T/ipykernel_57922/1990150254.py:1: DtypeWarning: Columns (0: onpromotion) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/train.csv",

In [4]:
print(df_train.shape)
df_train.head()

(125497040, 6)

   id       date  store_nbr  item_nbr  unit_sales onpromotion
0   0 2013-01-01         25    103665         7.0         NaN
1   1 2013-01-01         25    105574         1.0         NaN
2   2 2013-01-01         25    105575         2.0         NaN
3   3 2013-01-01         25    108079         1.0         NaN
4   4 2013-01-01         25    108701         1.0         NaN

In [5]:
df_train.dtypes

id                      int64
date           datetime64[us]
store_nbr               int64
item_nbr                int64
unit_sales            float64
onpromotion            object
dtype: object

In [6]:
print(df_train.shape)
df_train.describe()

(125497040, 6)

,id,date,store_nbr,item_nbr,unit_sales
count,1.254970e+08,125497040,1.254970e+08,1.254970e+08,1.254970e+08
mean,6.274852e+07,2015-09-15 16:43:18.789250,2.746458e+01,9.727692e+05,8.554865e+00
min,0.000000e+00,2013-01-01 00:00:00,1.000000e+00,9.699500e+04,-1.537200e+04
25%,3.137426e+07,2014-09-20 00:00:00,1.200000e+01,5.223830e+05,2.000000e+00
50%,6.274852e+07,2015-11-21 00:00:00,2.800000e+01,9.595000e+05,4.000000e+00
75%,9.412278e+07,2016-10-17 00:00:00,4.300000e+01,1.354380e+06,9.000000e+00
max,1.254970e+08,2017-08-15 00:00:00,5.400000e+01,2.127114e+06,8.944000e+04
std,3.622788e+07,NaN,1.633051e+01,5.205336e+05,2.360515e+01

In [7]:
df_train["onpromotion"].value_counts(dropna=False)

onpromotion
False    96028767
NaN      21657651
True      7810622
Name: count, dtype: int64

In [8]:
df_train.isnull().sum()

id                    0
date                  0
store_nbr             0
item_nbr              0
unit_sales            0
onpromotion    21657651
dtype: int64

In [10]:
df_train.duplicated("item_nbr").sum()

np.int64(125493004)

In [12]:
df_train.duplicated(["store_nbr", "item_nbr"]).sum()

np.int64(125322355)