In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/train.csv", parse_dates=["date"])

/var/folders/qd/66x74wkn0c7255_dtgx43p000000gn/T/ipykernel_62285/681075814.py:1: DtypeWarning: Columns (0: onpromotion) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/train.csv", parse_dates=["date"])

In [3]:
# df_train.set_index('date', inplace=True)
# df_train = df_train.drop(["id"], axis = 1)
print(df_train.shape)
df_train.head(10)

(125497040, 6)

   id       date  store_nbr  item_nbr  unit_sales onpromotion
0   0 2013-01-01         25    103665         7.0         NaN
1   1 2013-01-01         25    105574         1.0         NaN
2   2 2013-01-01         25    105575         2.0         NaN
3   3 2013-01-01         25    108079         1.0         NaN
4   4 2013-01-01         25    108701         1.0         NaN
5   5 2013-01-01         25    108786         3.0         NaN
6   6 2013-01-01         25    108797         1.0         NaN
7   7 2013-01-01         25    108952         1.0         NaN
8   8 2013-01-01         25    111397        13.0         NaN
9   9 2013-01-01         25    114790         3.0         NaN

# check if combination (date, store_nbr, item_nbr) is unique -> must show 0

In [5]:
df_train.groupby(["store_nbr", "item_nbr"]).size()

store_nbr  item_nbr
1          96995        187
           99197        185
           103520      1119
           103665      1358
           105574      1546
                       ...
54         2110456       47
           2113343        8
           2113914       36
           2116416       11
           2124052        1
Length: 174685, dtype: int64

In [6]:
df_train.duplicated(["store_nbr", "item_nbr"]).sum()

np.int64(125322355)

In [4]:
df_train.duplicated(["date", "store_nbr", "item_nbr"]).sum()

np.int64(0)

In [6]:
df_train["store_nbr"].value_counts(dropna=False)

store_nbr
44    3513089
45    3484244
47    3457407
3     3401264
46    3353890
49    3342531
8     3261184
48    3236523
50    3192566
6     3089799
2     2987840
51    2960031
7     2921204
37    2831691
4     2830554
9     2773790
24    2769889
38    2727731
5     2666691
39    2638036
27    2631714
11    2568282
1     2562153
41    2503919
28    2418816
23    2365697
31    2361724
34    2299422
36    2211162
18    2196682
17    2164020
40    2102799
25    2057020
33    1963485
43    1939694
15    1938678
53    1938255
19    1879155
12    1836583
16    1820035
14    1805941
26    1793082
10    1740482
13    1736728
20    1665985
54    1648867
30    1597862
29    1508959
42    1461683
35    1388104
21    1373419
32    1362615
22     923483
52     290581
Name: count, dtype: int64

In [7]:
df_train["item_nbr"].value_counts(dropna=False)

item_nbr
502331     83475
314384     83450
364606     83308
265559     83047
559870     82513
           ...
2126944        5
2123747        3
2122818        2
2015898        1
2011451        1
Name: count, Length: 4036, dtype: int64

In [19]:
df_test = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/test.csv")

In [20]:
print(df_test.shape)
df_test.head()

(3370464, 5)

          id        date  store_nbr  item_nbr  onpromotion
0  125497040  2017-08-16          1     96995        False
1  125497041  2017-08-16          1     99197        False
2  125497042  2017-08-16          1    103501        False
3  125497043  2017-08-16          1    103520        False
4  125497044  2017-08-16          1    103665        False

In [21]:
df_holi = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/holidays_events.csv")

In [22]:
print(df_holi.shape)
df_holi.head()

(350, 6)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [46]:
df_holi.tail()

           date        type    locale locale_name description  transferred
345  2017-12-22  Additional  National     Ecuador   Navidad-3        False
346  2017-12-23  Additional  National     Ecuador   Navidad-2        False
347  2017-12-24  Additional  National     Ecuador   Navidad-1        False
348  2017-12-25     Holiday  National     Ecuador     Navidad        False
349  2017-12-26  Additional  National     Ecuador   Navidad+1        False

In [23]:
df_items = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/items.csv")

In [24]:
print(df_items.shape)
df_items.head()

(4100, 4)

   item_nbr        family  class  perishable
0     96995     GROCERY I   1093           0
1     99197     GROCERY I   1067           0
2    103501      CLEANING   3008           0
3    103520     GROCERY I   1028           0
4    103665  BREAD/BAKERY   2712           1

# OIL

In [25]:
df_oil = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/oil.csv",
    parse_dates=["date"])

In [26]:
print(df_oil.shape)
df_oil.head()

(1218, 2)

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20

In [45]:
df_oil.tail()

           date  dcoilwtico
1213 2017-08-25       47.65
1214 2017-08-28       46.40
1215 2017-08-29       46.46
1216 2017-08-30       45.96
1217 2017-08-31       47.26

In [27]:
print(df_oil.dtypes)

date          datetime64[us]
dcoilwtico           float64
dtype: object

In [41]:
print(df_oil.dtypes)

date          datetime64[us]
dcoilwtico           float64
dtype: object

In [42]:
df_oil.isnull().sum()

date           0
dcoilwtico    43
dtype: int64

# STORES

In [28]:
df_stores = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/stores.csv")

In [29]:
print(df_stores.shape)
df_stores.head()

(54, 5)

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [30]:
print(df_stores.dtypes)

store_nbr    int64
city           str
state          str
type           str
cluster      int64
dtype: object

In [43]:
df_stores["city"].value_counts(dropna=False)

city
Quito            18
Guayaquil         8
Santo Domingo     3
Cuenca            3
Latacunga         2
Ambato            2
Machala           2
Manta             2
Cayambe           1
Riobamba          1
Ibarra            1
Guaranda          1
Puyo              1
Salinas           1
Daule             1
Babahoyo          1
Quevedo           1
Playas            1
Libertad          1
Loja              1
Esmeraldas        1
El Carmen         1
Name: count, dtype: int64

In [44]:
df_stores["state"].value_counts(dropna=False)

state
Pichincha                         19
Guayas                            11
Santo Domingo de los Tsachilas     3
Azuay                              3
Manabi                             3
Cotopaxi                           2
Tungurahua                         2
Los Rios                           2
El Oro                             2
Chimborazo                         1
Imbabura                           1
Bolivar                            1
Pastaza                            1
Santa Elena                        1
Loja                               1
Esmeraldas                         1
Name: count, dtype: int64

In [37]:
df_stores.isnull().sum()

store_nbr    0
city         0
state        0
type         0
cluster      0
dtype: int64

In [39]:
df_stores.duplicated().sum()

np.int64(0)

# TRANSACTIONS

In [31]:
df_transact = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/transactions.csv",
    parse_dates=["date"])

In [32]:
print(df_transact.shape)
df_transact.head()

(83488, 3)

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [33]:
print(df_transact.dtypes)

date            datetime64[us]
store_nbr                int64
transactions             int64
dtype: object

In [34]:
df_transact.isnull().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [35]:
df_transact.describe()

                             date     store_nbr  transactions
count                       83488  83488.000000  83488.000000
mean   2015-05-20 16:07:40.866232     26.939237   1694.602158
min           2013-01-01 00:00:00      1.000000      5.000000
25%           2014-03-27 00:00:00     13.000000   1046.000000
50%           2015-06-08 00:00:00     27.000000   1393.000000
75%           2016-07-14 06:00:00     40.000000   2079.000000
max           2017-08-15 00:00:00     54.000000   8359.000000
std                           NaN     15.608204    963.286644

In [36]:
df_transact.duplicated(["date", "store_nbr"]).sum()

np.int64(0)

In [47]:
df_train = df_train.merge(
    df_stores,
    on="store_nbr",
    how="left"
)

In [48]:
df_train.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,city,state,type,cluster
0,0,2013-01-01,25,103665,7.0,NaN,Salinas,Santa Elena,D,1
1,1,2013-01-01,25,105574,1.0,NaN,Salinas,Santa Elena,D,1
2,2,2013-01-01,25,105575,2.0,NaN,Salinas,Santa Elena,D,1
3,3,2013-01-01,25,108079,1.0,NaN,Salinas,Santa Elena,D,1
4,4,2013-01-01,25,108701,1.0,NaN,Salinas,Santa Elena,D,1

In [50]:
df_train = df_train.merge(
    df_items,
    on="item_nbr",
    how="left"
)

In [51]:
df_train.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,city,state,type,cluster,family,class,perishable
0,0,2013-01-01,25,103665,7.0,NaN,Salinas,Santa Elena,D,1,BREAD/BAKERY,2712,1
1,1,2013-01-01,25,105574,1.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1045,0
2,2,2013-01-01,25,105575,2.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1045,0
3,3,2013-01-01,25,108079,1.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1030,0
4,4,2013-01-01,25,108701,1.0,NaN,Salinas,Santa Elena,D,1,DELI,2644,1

In [52]:
df_train.tail()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,city,state,type,cluster,family,class,perishable
125497035,125497035,2017-08-15,54,2089339,4.0,False,El Carmen,Manabi,C,3,GROCERY I,1006,0
125497036,125497036,2017-08-15,54,2106464,1.0,True,El Carmen,Manabi,C,3,BEVERAGES,1148,0
125497037,125497037,2017-08-15,54,2110456,192.0,False,El Carmen,Manabi,C,3,BEVERAGES,1120,0
125497038,125497038,2017-08-15,54,2113914,198.0,True,El Carmen,Manabi,C,3,CLEANING,3040,0
125497039,125497039,2017-08-15,54,2116416,2.0,False,El Carmen,Manabi,C,3,GROCERY I,1060,0

In [53]:
df_test = df_test.merge(
    df_stores,
    on="store_nbr",
    how="left"
)

In [54]:
df_test.head()

,id,date,store_nbr,item_nbr,onpromotion,city,state,type,cluster
0,125497040,2017-08-16,1,96995,False,Quito,Pichincha,D,13
1,125497041,2017-08-16,1,99197,False,Quito,Pichincha,D,13
2,125497042,2017-08-16,1,103501,False,Quito,Pichincha,D,13
3,125497043,2017-08-16,1,103520,False,Quito,Pichincha,D,13
4,125497044,2017-08-16,1,103665,False,Quito,Pichincha,D,13

In [58]:
df_train.shape

(125497040, 13)

In [55]:
df_test = df_test.merge(
    df_items,
    on="item_nbr",
    how="left"
)

In [56]:
df_test.head()

,id,date,store_nbr,item_nbr,onpromotion,city,state,type,cluster,family,class,perishable
0,125497040,2017-08-16,1,96995,False,Quito,Pichincha,D,13,GROCERY I,1093,0
1,125497041,2017-08-16,1,99197,False,Quito,Pichincha,D,13,GROCERY I,1067,0
2,125497042,2017-08-16,1,103501,False,Quito,Pichincha,D,13,CLEANING,3008,0
3,125497043,2017-08-16,1,103520,False,Quito,Pichincha,D,13,GROCERY I,1028,0
4,125497044,2017-08-16,1,103665,False,Quito,Pichincha,D,13,BREAD/BAKERY,2712,1

In [57]:
df_test.shape

(3370464, 12)

In [59]:
df_train.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,city,state,type,cluster,family,class,perishable
0,0,2013-01-01,25,103665,7.0,NaN,Salinas,Santa Elena,D,1,BREAD/BAKERY,2712,1
1,1,2013-01-01,25,105574,1.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1045,0
2,2,2013-01-01,25,105575,2.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1045,0
3,3,2013-01-01,25,108079,1.0,NaN,Salinas,Santa Elena,D,1,GROCERY I,1030,0
4,4,2013-01-01,25,108701,1.0,NaN,Salinas,Santa Elena,D,1,DELI,2644,1

In [60]:
df_train.dtypes

id                      int64
date           datetime64[us]
store_nbr               int64
item_nbr                int64
unit_sales            float64
onpromotion            object
city                      str
state                     str
type                      str
cluster                 int64
family                    str
class                   int64
perishable              int64
dtype: object

In [61]:
df_train.isnull().sum()

id                    0
date                  0
store_nbr             0
item_nbr              0
unit_sales            0
onpromotion    21657651
city                  0
state                 0
type                  0
cluster               0
family                0
class                 0
perishable            0
dtype: int64