In [1]:
import pandas as pd
import numpy as np

In [2]:
# df_train = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/train.csv", parse_dates=["date"])

In [3]:
chunks = []

for chunk in pd.read_csv(
    "../data/raw/favorita-grocery-sales-forecasting/train.csv",
    parse_dates=["date"],
    chunksize=1_000_000
):
    filtered = chunk[chunk["date"] >= "2017-01-01"]

    if len(filtered):
        chunks.append(filtered)

df_train = pd.concat(chunks, ignore_index=True)

/var/folders/qd/66x74wkn0c7255_dtgx43p000000gn/T/ipykernel_70299/590564471.py:3: DtypeWarning: Columns (0: onpromotion) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(

In [4]:
df_train.shape

(23808261, 6)

In [5]:
df_train.head()

          id       date  store_nbr  item_nbr  unit_sales  onpromotion
0  101688779 2017-01-01         25     99197         1.0        False
1  101688780 2017-01-01         25    103665         7.0        False
2  101688781 2017-01-01         25    105574         1.0        False
3  101688782 2017-01-01         25    105857         4.0        False
4  101688783 2017-01-01         25    106716         2.0        False

In [6]:
df_train.dtypes

id                      int64
date           datetime64[us]
store_nbr               int64
item_nbr                int64
unit_sales            float64
onpromotion              bool
dtype: object

# drop id

In [7]:
# drop id
df_train = df_train.drop(["id"], axis = 1)

In [8]:
df_train.head()

        date  store_nbr  item_nbr  unit_sales  onpromotion
0 2017-01-01         25     99197         1.0        False
1 2017-01-01         25    103665         7.0        False
2 2017-01-01         25    105574         1.0        False
3 2017-01-01         25    105857         4.0        False
4 2017-01-01         25    106716         2.0        False

In [9]:
df_train.tail()

               date  store_nbr  item_nbr  unit_sales  onpromotion
23808256 2017-08-15         54   2089339         4.0        False
23808257 2017-08-15         54   2106464         1.0         True
23808258 2017-08-15         54   2110456       192.0        False
23808259 2017-08-15         54   2113914       198.0         True
23808260 2017-08-15         54   2116416         2.0        False

In [10]:
df_train["store_nbr"] = df_train["store_nbr"].astype("int8")

df_train["item_nbr"] = df_train["item_nbr"].astype("int32")

df_train["unit_sales"] = df_train["unit_sales"].astype("float32")

# df_train["lag1"] = df_train["lag1"].astype("float32")

# df_train["lag7"] = df_train["lag7"].astype("float32")

In [11]:
df_train["onpromotion"] = df_train["onpromotion"].map(
    {False: 0, True: 1}, 
    na_action="ignore"
)

# df_train["onpromotion"] = df_train["onpromotion"].map(
#     {False: 0, True: 1}, 
# ).fillna(-1)

# df_train["onpromotion"] = (
#             df_train["onpromotion"]
#             .map({True: 1, False: 0, 1: 1, 0: 0})
#             .fillna(self.fill_value)
#             .astype("int8")
#         )#

# df_train["onpromotion"] = df_train["onpromotion"].replace({False: 0, True: 1})

In [12]:
df_train.head()

        date  store_nbr  item_nbr  unit_sales  onpromotion
0 2017-01-01         25     99197         1.0            0
1 2017-01-01         25    103665         7.0            0
2 2017-01-01         25    105574         1.0            0
3 2017-01-01         25    105857         4.0            0
4 2017-01-01         25    106716         2.0            0

In [13]:
df_train[df_train['onpromotion'].isnull()]

Empty DataFrame
Columns: [date, store_nbr, item_nbr, unit_sales, onpromotion]
Index: []

In [14]:
df_train.isnull().sum()

date           0
store_nbr      0
item_nbr       0
unit_sales     0
onpromotion    0
dtype: int64

In [15]:
df_train.dtypes

date           datetime64[us]
store_nbr                int8
item_nbr                int32
unit_sales            float32
onpromotion             int64
dtype: object

In [16]:
df_train["onpromotion"] = df_train["onpromotion"].astype("int8")

# sort columns

In [17]:
# df_train = df_train.sort_values(["store_nbr", "item_nbr", "date"]).set_index("date")

In [18]:
# df_train.head()

# create lag

In [19]:
# # check groupby
# df_train.groupby(["store_nbr","item_nbr"]).head()

## lag 1

In [20]:
# df_train["lag1"] = (
#     df_train.groupby(["store_nbr","item_nbr"])["unit_sales"]
#       .shift(1)
# )

In [21]:
# df_train.head()

In [22]:
# df_train.tail()

## lag 7

In [23]:
# df_train["lag7"] = (
#     df_train.groupby(["store_nbr","item_nbr"])["unit_sales"]
#       .shift(7)
# )

In [24]:
# df_train.head(10)

In [25]:
# df_train.dtypes

In [26]:
# df_items = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/items.csv")

In [27]:
# df_stores = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/stores.csv")

# merge features

In [28]:
# df_train = df_train.merge(
#     df_stores,
#     on="store_nbr",
#     how="left"
# )

In [29]:
# df_train.head()

In [30]:
# df_train = df_train.merge(
#     df_items,
#     on="item_nbr",
#     how="left"
# )

In [31]:
# df_train.head()

In [32]:
# df_test = df_test.merge(
#     df_stores,
#     on="store_nbr",
#     how="left"
# )

In [33]:
# df_test.head()

In [34]:
# df_train.shape

In [35]:
# df_test = df_test.merge(
#     df_items,
#     on="item_nbr",
#     how="left"
# )

In [36]:
# df_test.head()

In [37]:
# df_test.shape

In [38]:
# df_train.head()

# plot

In [39]:
# # plot unit sales

# df_train["unit_sales"].plot()

In [40]:
# df_train = df_train.reset_index()
# df_train["date"] = pd.to_datetime(df_train["date"])

In [41]:
df_train.head()

        date  store_nbr  item_nbr  unit_sales  onpromotion
0 2017-01-01         25     99197         1.0            0
1 2017-01-01         25    103665         7.0            0
2 2017-01-01         25    105574         1.0            0
3 2017-01-01         25    105857         4.0            0
4 2017-01-01         25    106716         2.0            0

In [42]:
df_train["year"] = df_train["date"].dt.year
df_train["month"] = df_train["date"].dt.month
df_train["day"] = df_train["date"].dt.day
# df["day_of_week"] = df["date"].dt.dayofweek
# df["day_of_year"] = df["date"].dt.dayofyear
# df["week_of_year"] = df["date"].dt.isocalendar().week.astype(int)

In [43]:
df_train = df_train.drop(["date"], axis = 1)

In [44]:
df_train.head()

   store_nbr  item_nbr  unit_sales  onpromotion  year  month  day
0         25     99197         1.0            0  2017      1    1
1         25    103665         7.0            0  2017      1    1
2         25    105574         1.0            0  2017      1    1
3         25    105857         4.0            0  2017      1    1
4         25    106716         2.0            0  2017      1    1

In [109]:
df_train.dtypes

store_nbr         int8
item_nbr         int32
unit_sales     float32
onpromotion       int8
year              int8
month             int8
day               int8
dtype: object

In [46]:
df_train["year"] = df_train["year"].astype("int8")

df_train["month"] = df_train["month"].astype("int8")

df_train["day"] = df_train["day"].astype("int8")

In [47]:
df_train.dtypes

store_nbr         int8
item_nbr         int32
unit_sales     float32
onpromotion       int8
year              int8
month             int8
day               int8
dtype: object

In [48]:
categorical_features = [
    "store_nbr",
    "item_nbr",
]

numeric_features = [
    # "lag1",
    # "lag7",
    "onpromotion",
    "year",
    "month",
    "day",
]

In [49]:
# set X train and y train data

In [50]:
X_train = df_train.drop(["unit_sales"], axis=1)
y_train = df_train["unit_sales"]

print(X_train.shape)
print(y_train.shape)

(23808261, 6)
(23808261,)

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OrdinalEncoder
import lightgbm as lgb

In [56]:
numeric_transformer = SimpleImputer(strategy='mean')

In [57]:


categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OrdinalEncoder(
                handle_unknown="use_encoded_value",
                unknown_value=-1
            )
        )
    ]
)

In [58]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [59]:
# X_train_transformed = preprocessor.fit_transform(X_train)

# print(type(X_train_transformed))
# print(X_train_transformed.shape)

# print(X_train_transformed[:, 0:-1].dtype)
# # print(X_train_transformed[:, 2].dtype)

In [60]:
# num_processed = preprocessor.named_transformers_["num"].transform(
#     X_train[numeric_features]
# ).astype(np.float32)

# print(num_processed.dtype)
# print(num_processed.shape)

In [61]:


# model = RandomForestRegressor(
#     n_estimators=100,
#     max_depth=10,
#     min_samples_leaf=10,
#     random_state=42,
#     n_jobs=-1
# )

In [62]:
model=lgb.LGBMRegressor(
        n_estimators=1000, verbose=10, random_state=42, learning_rate=0.03
    )

In [63]:
model_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

In [64]:
model_pipeline.fit(X_train, y_train)

[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.317203
[LightGBM] [Debug] init for col-wise cost 0.000016 seconds, init for row-wise cost 0.236230 seconds
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.105025 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Debug] Using Sparse Multi-Val Bin
[LightGBM] [Info] Total Bins 354
[LightGBM] [Info] Number of data points in the train set: 23808261, number of used features: 6
[LightGBM] [Info] Start training from score 8.157544
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 18
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 20
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 18
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 11

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', SimpleImputer(),
                                                  ['onpromotion', 'year',
                                                   'month', 'day']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['store_nbr', 'item_nbr'])])),
                ('model',
                 LGBMRegressor(learning_rate=0.03, n_estimators=1000,
                               random_state=42, verbose=10))])

In [ ]:
# from xgboost import XGBRegressor

In [ ]:
# model_xgb = XGBRegressor(
#     n_estimators=500,
#     max_depth=8,
#     learning_rate=0.05,
#     subsample=0.8,
#     colsample_bytree=0.8,

#     # Important for large datasets
#     tree_method="hist",

#     objective="reg:squarederror",
#     eval_metric="rmse",

#     n_jobs=4,
#     random_state=42
# )

In [ ]:
# model_pipeline_xgb = Pipeline(
#     steps=[
#         ("preprocessor", preprocessor),
#         ("model", model_xgb)
#     ]
# )

In [ ]:
# model_xgb.fit(
#     X_train,
#     y_train,
#     verbose=50
# )

In [98]:
df_test = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/test.csv", parse_dates=["date"])

In [107]:
df_test.head()

   store_nbr  item_nbr  onpromotion  year  month  day
0          1     96995            0  2017      8   16
1          1     99197            0  2017      8   16
2          1    103501            0  2017      8   16
3          1    103520            0  2017      8   16
4          1    103665            0  2017      8   16

In [100]:
df_test = df_test.drop(["id"], axis = 1)

In [101]:
df_test["year"] = df_test["date"].dt.year
df_test["month"] = df_test["date"].dt.month
df_test["day"] = df_test["date"].dt.day

In [102]:
df_test = df_test.drop(["date"], axis = 1)

In [103]:
df_test["onpromotion"] = df_test["onpromotion"].map(
    {False: 0, True: 1}, 
    na_action="ignore"
)

In [108]:
df_test.dtypes

store_nbr       int8
item_nbr       int32
onpromotion     int8
year           int32
month          int32
day            int32
dtype: object

In [ ]:
df_test["store_nbr"] = df_test["store_nbr"].astype("int8")

df_test["item_nbr"] = df_test["item_nbr"].astype("int32")

# df_test["year"] = df_test["year"].astype("int8")

# df_test["month"] = df_test["month"].astype("int8")

# df_test["day"] = df_test["day"].astype("int8")

df_test["onpromotion"] = df_test["onpromotion"].astype("int8")

In [111]:
X_test = df_test
print(X_test.shape)

(3370464, 6)

In [113]:
y_test = model_pipeline.predict(X_test)

In [114]:
df_sample = pd.read_csv("../data/raw/favorita-grocery-sales-forecasting/sample_submission.csv")

In [115]:
df_sample["unit_sales"] = y_test

In [119]:
df_sample.head()

          id  unit_sales
0  125497040    0.000000
1  125497041    3.428835
2  125497042    3.428835
3  125497043    3.428835
4  125497044    3.428835

In [118]:
df_sample["unit_sales"] = np.clip(df_sample["unit_sales"], 0, None)

In [120]:
df_sample.to_csv("submission_lightgbm.csv", index=False)